let foo;
foo=1;
console.log(foo);
let bar=2;
foo=3;
console.log(foo);
console.log(typeof foo);
foo='hello';
console.log(foo);
console.log(typeof foo);
foo=1.4;
console.log(foo);
console.log(typeof foo);
foo=true;
console.log(foo);
console.log(typeof foo);
foo=false;
console.log(foo);
console.log(typeof foo);
foo=null;
console.log(foo);
console.log(typeof foo);
let baz;
console.log(baz);
console.log(typeof baz);
baz=undefined;
console.log(baz);
console.log(typeof baz);
foo=[1,2,3,4,5,'hello', true];
console.log(foo);
console.log(typeof foo);
foo={name:'Kaspar', age:29};
console.log(foo);
console.log(typeof foo);
